version: '2'
services:
  be:
    image: wecomp/be:latest
    restart: always
    depends_on:
      - orientdb-lb
    expose:
      - 8000
    environment:
      - VIRTUAL_HOST=*:9081

  fe:
    image: wecomp/fe:latest
    restart: always
    expose:
      - 80
    environment:
      - VIRTUAL_HOST=*:9080

  orientdb:
    image: orientdb:latest
    restart: always
    expose:
      - 2480
      - 2424
      - 2434
    environment:
      - ORIENTDB_ROOT_PASSWORD=root
      - TCP_PORTS=2424
    volumes:
      - /orientdb/backup
    command: /orientdb/bin/server.sh  -Ddistributed=true

  lb:
    image: dockercloud/haproxy
    links:
      - fe
      - be
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9080:9080
      - 9081:9081

  orientdb-lb:
    image: dockercloud/haproxy
    links:
      - orientdb
    expose:
      - 80
      - 2424
    ports:
      - 2480:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
