version: '2'
services:
  waiter:
    image: martin/wait
  be:
    image: wecomp/be:latest
    restart: always
    depends_on:
      - orientdb
    expose:
      - 8000
  fe:
    image: wecomp/fe:latest
    restart: always
    expose:
      - 80
  orientdb:
    image: orientdb:latest
    restart: always
    expose:
      - 2424
      - 2480
    environment:
      - ORIENTDB_ROOT_PASSWORD=root

  fe-lb:
    image: dockercloud/haproxy
    links:
      - fe
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9080:80

  be-lb:
    image: dockercloud/haproxy
    links:
      - be
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9081:80
